-- Script SQL para crear las tablas y secuencia en Oracle

-- Crear tabla DAF_TIPOS_IDENTIFICACION
CREATE TABLE DAF_TIPOS_IDENTIFICACION (
    CODIGO_TIPO_IDENTIFICACION VARCHAR2(10) PRIMARY KEY,
    NOMBRE_TIPO_IDENTIFICACION VARCHAR2(100) NOT NULL,
    ESTADO VARCHAR2(1) DEFAULT 'A'
);

-- Crear tabla MGM_PACIENTES
CREATE TABLE MGM_PACIENTES (
    ID_PACIENTE NUMBER PRIMARY KEY,
    CODIGO_TIPO_IDENTIFICACION VARCHAR2(10) NOT NULL,
    NUMERO_IDENTIFICACION VARCHAR2(20) NOT NULL UNIQUE,
    PRIMER_NOMBRE VARCHAR2(100) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR2(100),
    PRIMER_APELLIDO VARCHAR2(100) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(100),
    NOMBRE_COMPLETO VARCHAR2(400) NOT NULL,
    EMAIL VARCHAR2(200) NOT NULL,
    ESTADO VARCHAR2(1) DEFAULT 'A',
    FECHA_INGRESO DATE,
    USUARIO_INGRESO VARCHAR2(50),
    FECHA_MODIFICACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    CONSTRAINT FK_PACIENTE_TIPO_IDENT FOREIGN KEY (CODIGO_TIPO_IDENTIFICACION) 
        REFERENCES DAF_TIPOS_IDENTIFICACION(CODIGO_TIPO_IDENTIFICACION)
);

-- Crear secuencia para ID_PACIENTE
CREATE SEQUENCE MGM_SEQ_PACIENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Insertar tipos de identificación iniciales
INSERT INTO DAF_TIPOS_IDENTIFICACION (CODIGO_TIPO_IDENTIFICACION, NOMBRE_TIPO_IDENTIFICACION, ESTADO) 
VALUES ('CC', 'Cédula de Ciudadanía', 'A');

INSERT INTO DAF_TIPOS_IDENTIFICACION (CODIGO_TIPO_IDENTIFICACION, NOMBRE_TIPO_IDENTIFICACION, ESTADO) 
VALUES ('CE', 'Cédula de Extranjería', 'A');

INSERT INTO DAF_TIPOS_IDENTIFICACION (CODIGO_TIPO_IDENTIFICACION, NOMBRE_TIPO_IDENTIFICACION, ESTADO) 
VALUES ('TI', 'Tarjeta de Identidad', 'A');

INSERT INTO DAF_TIPOS_IDENTIFICACION (CODIGO_TIPO_IDENTIFICACION, NOMBRE_TIPO_IDENTIFICACION, ESTADO) 
VALUES ('PA', 'Pasaporte', 'A');

COMMIT;

